mongodb/docs-csharp

- source/fundamentals/authentication.txt
- source/fundamentals/connection.txt
- source/fundamentals/connection/connect.txt
- source/fundamentals/connection/connection-options.txt
- source/fundamentals/connection/mongo-client-settings.txt
- source/fundamentals/connection/network-compression.txt
- source/includes/mongodb-compatibility-table-csharp.rst
- source/includes/quick-start/next-steps.rst
The info on this page was pulled from the [Node.js Connection Options page](https://www.mongodb.com/docs/drivers/node/current/fundamentals/connection/connection-options/), the [URI Options spec](https://github.com/mongodb/specifications/blob/master/source/uri-options/uri-options.rst), and the [C# driver code](https://github.com/mongodb/mongo-csharp-driver). All values are correct to the best of my knowledge, though it will still get a technical review from the C# team.
JIRA - https://jira.mongodb.org/browse/DOCSP-24539
> DOCSP-24539 - C# Connection Options

- snooty.toml
- source/includes/code-examples/FindOneAsync.cs
- source/includes/code-examples/FindOneSync.cs
- source/usage-examples/findOne.txt
Updating the Find Usage examples page to have the examples be tabbed based on builders/linq and sync/async methods.
JIRA - <https://jira.mongodb.org/browse/DOCSP-24529>
> DOCSP-24529 Adding Tabs

- source/includes/code-examples/UpdateOne.cs
- source/includes/code-examples/UpdateOneAsync.cs
- source/usage-examples/updateOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24533
> DOCSP-24533 - C# UpdateOne Example

- source/index.txt
We can't actually build the site if there's no index.txt at the root so we'll know how the TOC works.
Staging: https://docs-mongodborg-staging.corp.mongodb.com/drivers/csharp/docsworker-xlarge/add-index/
Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6320e1999ef0f10115230251
> add index so it will build

- source/includes/code-examples/InsertOne.cs
- source/includes/code-examples/InsertOneAsync.cs
- source/usage-examples/insertOne.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-24531>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24531-insert-one-usage/usage-examples/insertOne/>
> DOCSP-24531 InsertOne usage example

- snooty.toml
- source/includes/code-examples/update-many/Restaurant.cs
- source/includes/code-examples/update-many/UpdateMany.cs
- source/includes/code-examples/update-many/UpdateManyAsync.cs
- source/usage-examples.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24534
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-24534-update-many/usage-examples/updateMany/
> DOCSP-24534 - UpdateMany usage example

- source/index.txt
- source/issues-and-help.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24556
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24556-issues-help-page/issues-and-help/
> DOCSP-24556: issues & help page

- source/faq.txt
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24557
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24557-FAQ-page/faq/
> DOCSP-24557: FAQ page

- source/includes/code-examples/insert-many/InsertMany.cs
- source/includes/code-examples/insert-many/InsertManyAsync.cs
- source/includes/code-examples/insert-many/Restaurant.cs
- source/usage-examples.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24532
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24532-insert-many/usage-examples/insertMany/#std-label-insert-runnable-example
> DOCSP-24532 Insert many usage example

- source/includes/code-examples/replace-one/ReplaceOne.cs
- source/includes/code-examples/replace-one/ReplaceOneAsync.cs
- source/includes/code-examples/replace-one/Restaurant.cs
- source/usage-examples.txt
- source/usage-examples/replaceOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24535
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-24535-replace-one/usage-examples/replaceOne/
> DOCSP-24535 - ReplaceOne page

- source/fundamentals.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/includes/fundamentals/code-examples/crud/delete.cs
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24549
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24549-delete-fundies/fundamentals/crud/write-operations/delete/
> DOCSP-24549: delete fundamentals

- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/includes/fundamentals/code-examples/crud/insert.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-24547
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24547-insert-fundamentals/fundamentals/crud/write-operations/insert/
> DOCSP-24547: insert fundamentals

- source/fundamentals.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/includes/code-examples/Restaurant.cs
- source/includes/fundamentals/code-examples/crud/Retrieve.cs
- source/index.txt
- source/usage-examples/findMany.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24545
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24545-retrieve/fundamentals/crud/read-operations/retrieve/
> DOCSP-24545 Fundamentals - Retrieve

- source/includes/code-examples/FindOne.cs
- source/includes/code-examples/FindOneAsync.cs
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/findMany.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25683
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-25683-usage-example-cleanup/usage-examples/ 
Changes made to all usage example pages
> DOCSP-25683 Usage example cleanup

- source/fundamentals.txt
- source/fundamentals/poco.txt
- source/includes/fundamentals/code-examples/poco.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-24551
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24551-POCO-page/fundamentals/poco/
> DOCSP-24551: POCOs page

- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24555
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-24555-api/
- [] Did you run a spell-check?
> DOCSP-24555 Add API Link

- source/fundamentals.txt
- source/fundamentals/authentication.txt
- source/fundamentals/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24543
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-24543-Enterprise-Authentication/fundamentals/enterprise-authentication/
> DOCSP-24543 Enterprise Authentication Mechanisms

- source/includes/code-examples/DeleteOne.cs
- source/includes/code-examples/DeleteOneAsync.cs
- source/includes/code-examples/FindMany.cs
- source/includes/code-examples/FindManyAsync.cs
- source/includes/code-examples/FindOne.cs
- source/includes/code-examples/FindOneAsync.cs
- source/includes/code-examples/InsertOne.cs
- source/includes/code-examples/InsertOneAsync.cs
- source/includes/code-examples/UpdateOne.cs
- source/includes/code-examples/UpdateOneAsync.cs
- source/includes/code-examples/delete-many/DeleteMany.cs
- source/includes/code-examples/delete-many/DeleteManyAsync.cs
- source/includes/code-examples/insert-many/InsertMany.cs
- source/includes/code-examples/insert-many/InsertManyAsync.cs
- source/includes/code-examples/replace-one/ReplaceOne.cs
- source/includes/code-examples/replace-one/ReplaceOneAsync.cs
- source/includes/code-examples/update-many/UpdateMany.cs
- source/includes/code-examples/update-many/UpdateManyAsync.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-26293
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-25293-expressions/usage-examples/findOne/#find-a-document-using-builders
(changed in most usage example pages)
> DOCSP-25293 Expressions in usage examples

- source/fundamentals/class-mapping.txt
Merging into upstream feature branch, which will then be merged into upstream/main.
[Original PR from Jordan's branch](https://github.com/mongodb/docs-csharp/pull/45)
JIRA - https://jira.mongodb.org/browse/DOCSP-26286
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-26286-class-maps/fundamentals/class-mapping/
> DOCSP-26286 - Class maps

- source/fundamentals.txt
- source/fundamentals/class-mapping.txt
- source/fundamentals/data-formats/poco.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26286
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-26286-class-mapping/fundamentals/class-mapping/
> DOCSP-26286 Class mapping

- source/fundamentals/data-formats.txt
- source/fundamentals/data-formats/guid-serialization.txt
[Here](https://mongodb.github.io/mongo-csharp-driver/2.18/reference/bson/guidserialization/) is the current page on GUID serialization for reference.
JIRA - https://jira.mongodb.org/browse/DOCSP-26327
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-26327-guid-serialization/fundamentals/data-formats/guid-serialization/
- - No--one warning about a broken link. Waiting on Jordan's ticket to fix.
- - No--see above.
> [DOCSP-26327] GUID Serialization

- snooty.toml
- source/fundamentals.txt
- source/fundamentals/connection/connection-options.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/specify-query.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/data-formats.txt
- source/index.txt
- source/issues-and-help.txt
- source/usage-examples.txt
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/findMany.txt
- source/usage-examples/findOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
- Cleaned up TODOs
- Added Read Operations to TOC
- [Added Usage Examples landing page](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-25528-cleanup/usage-examples/)
- [Added Fundamentals landing page](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-25528-cleanup/fundamentals/#std-label-csharp-fundamentals)
- [Added driver overview page](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-25528-cleanup/)
JIRA - https://jira.mongodb.org/browse/DOCSP-25528
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-25528-cleanup/
- [] Is this free of any warnings or errors in the …
> DOCSP-25528 cleanup

- source/fundamentals/builders.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/index.txt
- source/quick-reference.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24528
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-24528-quick-ref/quick-reference/
> [DOCSP-24528] Quick Reference 

- source/fundamentals/data-formats/bson.txt
- source/fundamentals/data-formats/guid-serialization.txt
- source/fundamentals/data-formats/poco.txt
- source/includes/fundamentals/code-examples/Bson.cs
- source/includes/fundamentals/code-examples/Clothing.cs
- source/includes/fundamentals/code-examples/poco.cs
- Are the sections well organized? Is each topic where a reader would expect to find it?
- Are any topics missing?
- Are the sections well organized?
- Are all topics explained clearly and correctly?
- Is anything missing?
- Are there any upcoming changes to the driver that will affect the documentation?
- Are all code examples following best practices?
> Data Formats

- source/fundamentals/authentication.txt
- source/fundamentals/enterprise-authentication.txt
- Are the sections well organized? Is each topic where a reader would expect to find it?
- Are any topics missing?
- Are the sections well organized?
- Are all topics explained clearly and correctly?
- Is anything missing?
- Are there any upcoming changes to the driver that will affect the documentation?
- Are all code examples following best practices?
> Authentication

- source/fundamentals/class-mapping.txt
- Are the sections well organized? Is each topic where a reader would expect to find it?
- Are any topics missing?
- Are the sections well organized?
- Are all topics explained clearly and correctly?
- Is anything missing?
- Are there any upcoming changes to the driver that will affect the documentation?
- Are all code examples following best practices?
> Class Mapping

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/specify-query.txt
- source/fundamentals/crud/write-operations/change.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/linq.txt
- source/includes/code-examples/delete-many/Restaurant.cs
- source/includes/code-examples/delete-one/Restaurant.cs
- source/includes/code-examples/find-many/Restaurant.cs
- source/includes/code-examples/find-one/Restaurant.cs
- source/includes/code-examples/insert-many/Restaurant.cs
- source/includes/code-examples/insert-one/Restaurant.cs
- source/includes/code-examples/replace-one/Restaurant.cs
- source/includes/code-examples/update-one/Restaurant.cs
- source/includes/convention-pack-note.rst
- source/includes/fundamentals/code-examples/crud/Restaurant.cs
- source/includes/fundamentals/code-examples/crud/change/Restaurant.cs
- source/includes/fundamentals/code-examples/crud/delete.cs
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/findMany.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
Staging - 
[Removing object from models](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/tech-review-mvp-changes/usage-examples/deleteMany/)
[Added note about convention pack](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/tech-review-mvp-changes/fundamentals/linq/)
> conventionpack note and removing object in models

- source/includes/code-examples/Address.cs
- source/includes/code-examples/GradeEntry.cs
- source/includes/code-examples/Restaurant.cs
- source/usage-examples/deleteOne.txt
- source/usage-examples/findMany.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/updateOne.txt
Staging - 
[Usage Examples](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/review-updates/usage-examples/findOne/)
> Review updates

- source/includes/fundamentals/code-examples/builders.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-27275
> DOCSP-27275 - Add Console to WriteLine

- source/fundamentals/builders.txt
- source/includes/fundamentals/code-examples/builders.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-27478
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27478-atlas-search/fundamentals/builders/#build-an-atlas-search-query
> DOCSP-27478 Atlas search

- source/index.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27658
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-27658-whats-new/whats-new/
> Docsp 27658 - whats new page

- source/fundamentals/connection/connection-options.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27678
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27678-broken-links/fundamentals/connection/connection-options/#connection-options-1
> broken links

- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-27851>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27851-update-course-link/#take-the-free-online-course-taught-by-mongodb
> DOCSP-27851: fix link to course

- source/index.txt
- source/previous-versions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-27916>
Staging:
[Index](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27916-link-gh-docs/)
[Previous Versions](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27916-link-gh-docs/previous-versions/)
> DOCSP-27916: link GH docs

- source/fundamentals/connection/connect.txt
- source/includes/fundamentals/code-examples/connection/AtlasConnection.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-27919
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27919-connection-stableapi/fundamentals/connection/connect/#connect-to-atlas
> DOCSP-27919: stableapi connection for atlas

- source/quick-reference.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27680
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27680-remove-pocos/quick-reference/
- [] Did you run a spell-check?
> DOCSP-27680 Remove POCOs from quick reference

- source/fundamentals.txt
- source/fundamentals/atlas-search.txt
- source/fundamentals/builders.txt
- source/includes/atlas-search-support-note.rst
- source/includes/code-examples/Address.cs
- source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-27882
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27882-Atlas-search-page/fundamentals/atlas-search/
> DOCSP-27882 Atlas search page

- source/includes/fundamentals/code-examples/connection/AtlasConnection.cs
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/030623-fix-connection/fundamentals/connection/connect/#connect-to-atlas
> Fix connection snippet variable name

- source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-28125>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-28125-shared-compat/compatibility/
> DOCSP-28125: Use shared compatibility tables

- source/fundamentals/authentication.txt
- [Dima's notes on AWS in the .NET driver](https://gist.github.com/DmitryLukyanov/48662ff9c36cb43753d9b190323873d2)
- [Java AWS auth docs](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/auth/#mongodb-aws)
JIRA - https://jira.mongodb.org/browse/DOCSP-27247
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-27247-aws-auth/fundamentals/authentication/
> docsp-27247 - aws auth

- source/includes/fundamentals/code-examples/connection/AtlasConnection.cs
JIRA - [DOCSP-27919](https://jira.mongodb.org/browse/DOCSP-27919)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/stable-api-updates-cleanup/fundamentals/connection/connect/#connect-to-atlas
> match conventions

- source/fundamentals/atlas-search.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28791
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-28791-search-types/fundamentals/atlas-search/#equals
> docsp-28791 - search types

- source/includes/code-examples/delete-many/DeleteMany.cs
- source/includes/code-examples/delete-many/DeleteManyAsync.cs
- source/includes/code-examples/delete-one/DeleteOne.cs
- source/includes/code-examples/delete-one/DeleteOneAsync.cs
- source/includes/code-examples/find-many/FindMany.cs
- source/includes/code-examples/find-many/FindManyAsync.cs
- source/includes/code-examples/find-one/FindOne.cs
- source/includes/code-examples/find-one/FindOneAsync.cs
- source/includes/code-examples/insert-many/InsertMany.cs
- source/includes/code-examples/insert-many/InsertManyAsync.cs
- source/includes/code-examples/insert-one/InsertOne.cs
- source/includes/code-examples/insert-one/InsertOneAsync.cs
- source/includes/code-examples/replace-one/ReplaceOne.cs
- source/includes/code-examples/replace-one/ReplaceOneAsync.cs
- source/includes/code-examples/update-many/UpdateMany.cs
- source/includes/code-examples/update-many/UpdateManyAsync.cs
- source/includes/code-examples/update-one/UpdateOne.cs
- source/includes/code-examples/update-one/UpdateOneAsync.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-28590
Staging - Changes don't show in staging
- [] Did you run a spell-check?
> DOCSP-28590 Add POCOs to fully runnable examples

- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28069
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-28069-mongodb-analyzer-link/
> DOCSP-28069 MongoDB Analyzer Link

- source/faq.txt
- source/fundamentals/connection/connect.txt
JIRA - [DOCSP-28557](https://jira.mongodb.org/browse/DOCSP-28557)
Staging - [FAQ](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-28557-reuse-client/faq/#how-does-connection-pooling-work-in-the-.net-c--driver-) | [Connection Guide](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-28557-reuse-client/fundamentals/connection/connect/#connection-uri)
> DOCSP-28557: reuse client & connection pool faq

- source/fundamentals/connection.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28073
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-28073-aws-lambda-link/fundamentals/connection/
**Also made a drawer item under "Connection" that links to AWS Lambda page.**
> DOCSP-28073 Added link to Atlas AWS Lambda connection page

- source/index.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29626
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-29626-move-WN/#what-s-new
and see left nav
> DOCSP-29626: move whats new in nav + new anchor

- source/connection-troubleshooting.txt
- source/faq.txt
- source/fundamentals/connection/connect.txt
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-29490>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-29490/connection-troubleshooting/>
> DOCSP-29490: Created Connection Troubleshooting Guide

- source/fundamentals/upgrade.txt
- source/index.txt
- source/upgrade.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-27661>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-27661-Upgrade-Driver-page/>
> DOCSP-27661: Upgrade Driver page

- source/includes/quick-start/Program.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30836>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-30836-URI-error-message/)
> DOCSP-30836-URI-error

- source/fundamentals/authentication.txt
- source/fundamentals/stable-api.txt
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/typo-check/fundamentals/authentication/#x.509
https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/typo-check/fundamentals/stable-api/
> Typo fixes

- source/fundamentals/connection.txt
- source/fundamentals/connection/network-compression.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32850
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/docsp-32850-network-compression/fundamentals/connection/network-compression/
> docsp-32850 - network compression

- config/redirects
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31826>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-31826-update-titles/fundamentals/crud/write-operations/modify/>
Redirects - 
Redirect 301 /docs/drivers/csharp/2.19/fundamentals/crud/write-operations/change/ https://www.mongodb.com/docs/drivers/csharp/2.19/fundamentals/crud/write-operations/modify/
Redirect 301 /docs/drivers/csharp/2.20/fundamentals/crud/write-operations/change/ https://www.mongodb.com/docs/drivers/csharp/2.20/fundamentals/crud/write-operations/modify/
Redirect 301 /docs/drivers/csharp/2.21/fundamentals/crud/write-operations/change/ …
> DOCSP-31826: Update page titles

- .github/workflows/vale-tdbx.yml
Fix the trigger for the Vale GH action
> Fix the trigger for the Vale GH action

- source/facets.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-32483>
Hi @mongoKart - here's the face.toml file for the csharp repo.  Please merge if everything looks good!
Thank you!
Sarah
> DOCSP-32483 programmatic tagging script for csharp repo

- source/index.txt
Hey @mongoKart!
Here are the correct csharp tags for the top 250 manual tagging project.  Please merge if everything looks good too you!  You might notice that the facet type has changed to facet name, and that's per DOP.  I'll send changes as I go back and update my previous PRs, but this one is good to go.
Thanks!
Sarah
JIRA - <https://jira.mongodb.org/browse/DOCSP-27817>
> DOCSP-27817 manual tagging for csharp top 250 pages

- source/compatibility.txt
- source/includes/lifecycle-schedule-callout.rst
- source/index.txt
Note: build warning related to facets, not expected to impact publish.
JIRA - <https://jira.mongodb.org/browse/DOCSP-30911>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/csharp/DOCSP-30911-server-support/compatibility/#compatibility-table-legend
> DOCSP-30911: Add server lifecycle support callout

- source/fundamentals.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-29771>
Staging -
> DOCSP-29771: Add meta descriptions

- source/includes/fact-environments.rst
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32297>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-32297/>
Build -<https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6512f72c492df295cff1f240>
> DOCSP-32297 adds compatibility info to landing page

- config/redirects
[PR Reviewing Guidelines](https://github.com/mongodb/docs-csharp/blob/master/REVIEWING.md)
JIRA - N/A
Staging - N/A
> fix version redirects

- source/fundamentals/data-formats.txt
- source/fundamentals/data-formats/serialization.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26326
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-26326-serialization/fundamentals/data-formats/serialization/
> DOCSP-26326 serialization

- source/fundamentals/data-formats.txt
- source/fundamentals/data-formats/serialization.txt
(cherry picked from commit 76311e2c8a7b8c437f9696071a7830ffdc19c113)
> DOCSP-26326 serialization (#120)

- source/connection-troubleshooting.txt
- source/faq.txt
* typo fixes
* Chris suggestion
(cherry picked from commit be2b8335504ababead03896a72da9d6fc6ac9202)
> Typo fixes (#133)

- source/fundamentals/atlas-search.txt
> Add taxonomy to atlas search page

- source/faq.txt
- source/fundamentals/authentication.txt
- source/fundamentals/data-formats/poco.txt
> Add taxonomy tagging

- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-34265
Staging - https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-34265-ef-links/
> docsp-34265 - ef links

- source/usage-examples/facets.toml
Hey @ccho-mongodb - here's the additional facet.toml file for the c# driver.
JIRA - <https://jira.mongodb.org/browse/DOCSP-31343>
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/csharp/DOCSP-31343/>
> DOCSP-31343 additional facet.toml for docs-csharp

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/modify.txt
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-29462>
Staging:
- [retrieve](https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCSP-29462-csharp-labs/fundamentals/crud/read-operations/retrieve/)
- [update](https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCSP-29462-csharp-labs/fundamentals/crud/write-operations/modify/)
- [insert](https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCSP-29462-csharp-labs/fundamentals/crud/write-operations/insert/)
> DOCSP-29462: EMBED csharp labs

- source/faq.txt
- source/fundamentals/authentication.txt
- source/fundamentals/builders.txt
- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/modify.txt
- source/fundamentals/enterprise-authentication.txt
- source/fundamentals/serialization.txt
- source/fundamentals/serialization/class-mapping.txt
- source/fundamentals/serialization/poco.txt
- source/quick-reference.txt
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/findMany.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-35032
Staging - https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-35032-update-links/
> DOCSP-35032 - update links

- source/includes/code-examples/delete-many/DeleteMany.cs
- source/includes/code-examples/delete-many/DeleteManyAsync.cs
- source/includes/code-examples/delete-one/DeleteOne.cs
- source/includes/code-examples/delete-one/DeleteOneAsync.cs
- source/includes/code-examples/find-many/FindMany.cs
- source/includes/code-examples/find-many/FindManyAsync.cs
- source/includes/code-examples/find-one/FindOne.cs
- source/includes/code-examples/find-one/FindOneAsync.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-3417>
- https://jira.mongodb.org/browse/DOCSP-34911 DeleteMany
- https://jira.mongodb.org/browse/DOCSP-34912 DeleteManyAsync
- https://jira.mongodb.org/browse/DOCSP-34913 DeleteOne
- https://jira.mongodb.org/browse/DOCSP-34914 DeleteOneAsync
- https://jira.mongodb.org/browse/DOCSP-34915 FindMany
- https://jira.mongodb.org/browse/DOCSP-34916 FindManyAsync
- https://jira.mongodb.org/browse/DOCSP-34917 FindOne
- https://jira.mongodb.org/browse/DOCSP-34918 FindOneAsync
> [C#] CodeWhisperer Code Comments - Part 1

- source/includes/code-examples/insert-many/InsertMany.cs
- source/includes/code-examples/insert-many/InsertManyAsync.cs
- source/includes/code-examples/insert-one/InsertOne.cs
- source/includes/code-examples/insert-one/InsertOneAsync.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-3417>
- https://jira.mongodb.org/browse/DOCSP-34919 InsertMany
- https://jira.mongodb.org/browse/DOCSP-34920 InsertManyAsync
- https://jira.mongodb.org/browse/DOCSP-34921 InsertOne
- https://jira.mongodb.org/browse/DOCSP-34922 InsertOneAsync 
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-34178-p2/fundamentals/crud/write-operations/insert/>
- I'm getting the same error that I was [previously told to ignore](https://mongodb.slack.com/archives/C01UNG147QV/p1701111280046349)
> [C#] CodeWhisperer Code Comments - Part 2

- source/includes/fundamentals/code-examples/poco.cs
- source/includes/fundamentals/code-examples/specify-query/FindAndPOCO.cs
- source/includes/fundamentals/code-examples/specify-query/FindEqPOCO.cs
- source/includes/fundamentals/code-examples/specify-query/FindGtPOCO.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-34178>
- https://jira.mongodb.org/browse/DOCSP-34945 poco
- https://jira.mongodb.org/browse/DOCSP-34967 FindAndPOCO
- https://jira.mongodb.org/browse/DOCSP-34969 FindEqPOCO
- https://jira.mongodb.org/browse/DOCSP-34973 FindGtPOCO
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-34178-p5/fundamentals/crud/read-operations/specify-query/>
> [C#] CodeWhisperer Code Comments - Part 5

- source/includes/fundamentals/code-examples/builders.cs
- source/includes/fundamentals/code-examples/specify-query/FindAndBuilder.cs
- source/includes/fundamentals/code-examples/specify-query/FindEqBuilder.cs
- source/includes/fundamentals/code-examples/specify-query/FindExistsBuilder.cs
- source/includes/fundamentals/code-examples/specify-query/FindGtBuilder.cs
- source/includes/fundamentals/code-examples/specify-query/FindRegexBuilder.cs
- source/includes/fundamentals/code-examples/specify-query/FindSizeBuilder.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-34178>
- https://jira.mongodb.org/browse/DOCSP-34947 builders
- https://jira.mongodb.org/browse/DOCSP-34966 FindAndBuilder
- https://jira.mongodb.org/browse/DOCSP-34968 FindEqBuilder
- https://jira.mongodb.org/browse/DOCSP-34970 FindExistsBuilder
- https://jira.mongodb.org/browse/DOCSP-34972 FindGtBuilder
- https://jira.mongodb.org/browse/DOCSP-34974 FindRegexBuilder
- https://jira.mongodb.org/browse/DOCSP-34975 FindSizeBuilder
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-34178-p6/fundamentals/crud/read-operations/specify-query/>
> [C#] CodeWhisperer Code Comments - Part 6

- source/fundamentals/connection/connect.txt
- source/fundamentals/connection/connection-options.txt
- source/fundamentals/crud/read-operations/count.txt
- source/includes/fundamentals/code-examples/Bson.cs
- source/includes/fundamentals/code-examples/CountDocuments.cs
- source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
- source/includes/fundamentals/code-examples/connection/AtlasConnection.cs
- source/includes/fundamentals/code-examples/connection/LocalConnection.cs
- source/includes/fundamentals/code-examples/connection/LocalConnectionConfig.cs
- source/includes/fundamentals/code-examples/connection/MongoClientSettings.cs
- source/includes/fundamentals/code-examples/connection/MongoClientSettingsConfig.cs
- source/includes/fundamentals/code-examples/connection/ReplicaSetConnection.cs
- source/includes/fundamentals/code-examples/connection/StandaloneConnection.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-34178>
- https://jira.mongodb.org/browse/DOCSP-34951 Bson.cs
- https://jira.mongodb.org/browse/DOCSP-34952 AtlasSearchExamples.cs
- https://jira.mongodb.org/browse/DOCSP-34953 AtlasConnection.cs
- https://jira.mongodb.org/browse/DOCSP-34954 LocalConnection.cs 
- https://jira.mongodb.org/browse/DOCSP-34955  LocalConnectionConfig.cs
- https://jira.mongodb.org/browse/DOCSP-34956 MongoClientSettings.cs 
- https://jira.mongodb.org/browse/DOCSP-34958 MongoClientSettingsConfig.cs
- https://jira.mongodb.org/browse/DOCSP-34959 ReplicaSetConnection.cs 
- https://jira.mongodb.org/browse/DOCSP-34960 StandaloneConnection.cs
Staging
- …
> [C#] CodeWhisperer Code Comments - Part 7

- source/fundamentals/crud/read-operations/retrieve.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-34346
Staging - https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-34346-print-cursor/fundamentals/crud/read-operations/retrieve/#example
> DOCSP-34346 - Expanded cursor example

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-35888
Staging - (No staging changes) https://preview-mongodbjordansmith721.gatsbyjs.io/csharp/DOCSP-35888-missing-redirect/ 
mut-redirect output for added lines:
Redirect 301 /docs/drivers/csharp/master https://www.mongodb.com/docs/drivers/csharp/upcoming/
Redirect 301 /docs/drivers/csharp/v2.19/fundamentals/data-formats/bson https://www.mongodb.com/docs/drivers/csharp/v2.19/fundamentals/bson/
Redirect 301 /docs/drivers/csharp/v2.20/fundamentals/data-formats/bson https://www.mongodb.com/docs/drivers/csharp/v2.20/fundamentals/bson/
Redirect 301 /docs/drivers/csharp/v2.21/fundamentals/data-formats/bson …
> DOCSP-35888 Add missing redirects

- source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36099>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCSP-36099-typo-fix-linq/fundamentals/linq/#supported-methods:~:text=maximum%20specified%20value-,OfType,-Returns%20documents%20that
> DOCSP-36099-fix-typo

- source/fundamentals/authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36948>
Staging - <https://preview-mongodbsarahsimpers.gatsbyjs.io/csharp/DOCSP-36948/fundamentals/authentication/#scram-sha-1>
Build - <https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d4bbaf71111659826b4cc2>
> (DOCSP-36948) Changes authorization to authentication in one spot

- source/fundamentals/authentication.txt
(cherry picked from commit 762a1c2d191135e881608021d354f9bed9a5488c)
> (DOCSP-36948) Changes authorization to authentication in one spot (#163)

- source/includes/code-examples/GradeEntry.cs
- source/includes/code-examples/delete-many/DeleteMany.cs
- source/includes/code-examples/delete-many/DeleteManyAsync.cs
- source/includes/code-examples/delete-one/DeleteOne.cs
- source/includes/code-examples/delete-one/DeleteOneAsync.cs
- source/includes/code-examples/find-many/FindMany.cs
- source/includes/code-examples/find-many/FindManyAsync.cs
- source/includes/code-examples/find-one/FindOne.cs
- source/includes/code-examples/find-one/FindOneAsync.cs
- source/includes/code-examples/insert-many/InsertMany.cs
- source/includes/code-examples/insert-many/InsertManyAsync.cs
- source/includes/code-examples/insert-one/InsertOne.cs
- source/includes/code-examples/insert-one/InsertOneAsync.cs
- source/includes/code-examples/replace-one/ReplaceOne.cs
- source/includes/code-examples/replace-one/ReplaceOneAsync.cs
- source/includes/code-examples/update-many/UpdateMany.cs
- source/includes/code-examples/update-many/UpdateManyAsync.cs
- source/includes/code-examples/update-one/UpdateOne.cs
- source/includes/code-examples/update-one/UpdateOneAsync.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-37121
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/csharp/DOCSP-37121-usage-example-fixes/usage-examples/ (links to "fully runnable example" won't be updated on staging until this PR is merged in)
- [] Did you run a spell-check?
- [N/A] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?
> DOCSP-37121 Fix broken usage example code

- source/includes/code-examples/GradeEntry.cs
- source/includes/code-examples/delete-many/DeleteMany.cs
- source/includes/code-examples/delete-many/DeleteManyAsync.cs
- source/includes/code-examples/delete-one/DeleteOne.cs
- source/includes/code-examples/delete-one/DeleteOneAsync.cs
- source/includes/code-examples/find-many/FindMany.cs
- source/includes/code-examples/find-many/FindManyAsync.cs
- source/includes/code-examples/find-one/FindOne.cs
- source/includes/code-examples/find-one/FindOneAsync.cs
- source/includes/code-examples/insert-many/InsertMany.cs
- source/includes/code-examples/insert-many/InsertManyAsync.cs
- source/includes/code-examples/insert-one/InsertOne.cs
- source/includes/code-examples/insert-one/InsertOneAsync.cs
- source/includes/code-examples/replace-one/ReplaceOne.cs
- source/includes/code-examples/replace-one/ReplaceOneAsync.cs
- source/includes/code-examples/update-many/UpdateMany.cs
- source/includes/code-examples/update-many/UpdateManyAsync.cs
- source/includes/code-examples/update-one/UpdateOne.cs
- source/includes/code-examples/update-one/UpdateOneAsync.cs
(cherry picked from commit bfb4e6ff912b3dbdf8775e0372ef10ba13929091)
> fix broken usage example code (#167)

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37188>
Staging
- [Retrieve](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-37188/fundamentals/crud/read-operations/retrieve/)
- [Insert](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-37188/fundamentals/crud/write-operations/insert/)
- [Modify](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-37188/fundamentals/crud/write-operations/modify/)
> [C#] Build errors: Instruqt titles

- source/fundamentals/atlas-search.txt
- source/fundamentals/logging.txt
- source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
- source/quick-start.txt
JIRA
- https://jira.mongodb.org/browse/DOCSP-37267
- https://jira.mongodb.org/browse/DOCSP-37270
- https://jira.mongodb.org/browse/DOCSP-37263
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/v2.24/
> Backport docs updates v2.24

- source/fundamentals/logging.txt
**Updating the page based on a ticket comment after the initial PR was merged**
JIRA - <https://jira.mongodb.org/browse/DOCSP-37270>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCSP-37270-logging-pkg/fundamentals/logging/>
> DOCSP-37270: update logging pkg

- source/quick-start.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37263>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCSP-37263-env-var-set-option/quick-start/#set-your-connection-string>
> DOCSP-37263: add set option for PS users

- source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38680>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/csharp/DOCSP-38680-shared-compatibility/compatibility/
> DOCSP-38680: update latest version to use shared compat tables

- source/fundamentals/atlas-search.txt
- source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-33940
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/csharp/DOCSP-33940-embedded-documents/fundamentals/atlas-search/#embedded-document
> DOCSP-33940 Atlas Search Embedded Documents

- source/fundamentals.txt
- source/fundamentals/time-series.txt
- source/includes/fundamentals/code-examples/TimeSeries.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-38307>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-38307-time-series-collections/fundamentals/time-series/>
> DOCSP-38307: Add time series collections page

- source/faq.txt
- source/usage-examples.txt
JIRA - [DOCSP-37264](https://jira.mongodb.org/browse/DOCSP-37264)
Staging
* https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-37264-new-sync-vs-async/faq/
* https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-37264-new-sync-vs-async/usage-examples/
> DOCSP-37264: Add text comparing async vs sync/LINQ vs builder usecases

- source/fundamentals.txt
- source/fundamentals/aggregation.txt
- source/fundamentals/aggregations.txt
- source/fundamentals/builders.txt
- source/fundamentals/time-series.txt
- source/includes/fundamentals/code-examples/Aggregation.cs
- source/includes/fundamentals/code-examples/BuilderAggregation.cs
- source/includes/fundamentals/code-examples/LinqAggregation.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-38312>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/38312-aggregations/fundamentals/aggregation/>
> 38312: Aggregations page

- source/fundamentals/builders.txt
- source/fundamentals/linq.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-34852
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/csharp/DOCSP-34852-support-out/fundamentals/builders/#write-pipeline-results-to-a-collect
> DOCSP-34852 Support $out

- source/connection-troubleshooting.txt
- source/fundamentals/authentication.txt
JIRA - [DOCSP-40417](https://jira.mongodb.org/browse/DOCSP-40417)
Staging
* https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-40417-ephemeral-cert/connection-troubleshooting/
* https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-40417-ephemeral-cert/fundamentals/authentication/
> DOCSP-40417: Add X509 troubleshooting steps

- source/fundamentals/enterprise-authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41035>
Staging - <https://preview-mongodbstephmarie17.gatsbyjs.io/csharp/docsp-41035-updateConnectionString/fundamentals/enterprise-authentication/#mongodb-oidc>
> Clarify using commas in connection strings

- source/fundamentals/enterprise-authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41035> (part of backporting changes to complete this ticket)
Staging - <https://preview-mongodbstephmarie17.gatsbyjs.io/csharp/v2.25/fundamentals/enterprise-authentication/#mongodb-oidc>
This PR is an update to this docs version for the update to master and newer versions.
> Clarify commas in OIDC

- source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43732
<li><a href=https://deploy-preview-237--mongodb-docs-csharp.netlify.app/upgrade>upgrade</a></li>
> DOCSP-43732 - Remove [Serializable]

- source/upgrade/v3.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43918
<li><a href=https://deploy-preview-243--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
> DOCSP-43918 - Removed APIs

- source/upgrade/v3.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43733
<li><a href=https://deploy-preview-246--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
> DOCSP-43733 - Default JSON mode

- snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-43972
https://deploy-preview-247--mongodb-docs-csharp.netlify.app/
> DOCSP-43972 EOL v2.19

- source/upgrade/v3.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43933
<li><a href=https://deploy-preview-249--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
> DOCSP-43933 - Single Credential

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-44516
No pages to preview
> DOCSP-44516 - v3.0

- source/upgrade/v3.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44476
<li><a href=https://deploy-preview-256--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
> DOCSP-44476 - BsonValue methods

- source/fundamentals/enterprise-authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44588>
<li><a href=https://deploy-preview-266--mongodb-docs-csharp.netlify.app/fundamentals/enterprise-authentication>fundamentals/enterprise-authentication</a></li>
> DOCSP-44588: Fix broken 3.0 link

- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44588>
<li><a href=https://deploy-preview-267--mongodb-docs-csharp.netlify.app/index>index</a></li>
> DOCSP-44588: Add trailing slash to Analyzer URL

- source/fundamentals/crud/read-operations/count.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44438
<li><a href=https://deploy-preview-268--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations/count>fundamentals/crud/read-operations/count</a></li>
> DOCSP-44438 - Remove nil

- source/fundamentals.txt
- source/fundamentals/connection.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/serialization.txt
- source/index.txt
- source/upgrade.txt
- source/usage-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44897>
<li><a href=https://deploy-preview-287--mongodb-docs-csharp.netlify.app/fundamentals>fundamentals</a></li><li><a href=https://deploy-preview-287--mongodb-docs-csharp.netlify.app/fundamentals/connection>fundamentals/connection</a></li><li><a href=https://deploy-preview-287--mongodb-docs-csharp.netlify.app/fundamentals/crud>fundamentals/crud</a></li><li><a href=https://deploy-preview-287--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations>fundamentals/crud/read-operations</a></li><li><a href=https://deploy-preview-287--mongodb-docs-csharp.netlify.app/fundamentals/crud/write-operations>fundamentals/crud/write-operations</a></li><li><a …
> DOCSP-44897 TOC Relabel

- source/upgrade/v3.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44692>
<li><a href=https://deploy-preview-297--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
> DOCSP-44692: Cluster event breaking change

- source/fundamentals.txt
- source/fundamentals/connection.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/serialization.txt
- source/index.txt
- source/upgrade.txt
- source/usage-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44897>
<li><a href=https://deploy-preview-296--mongodb-docs-csharp.netlify.app/fundamentals>fundamentals</a></li><li><a href=https://deploy-preview-296--mongodb-docs-csharp.netlify.app/fundamentals/connection>fundamentals/connection</a></li><li><a href=https://deploy-preview-296--mongodb-docs-csharp.netlify.app/fundamentals/crud>fundamentals/crud</a></li><li><a href=https://deploy-preview-296--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations>fundamentals/crud/read-operations</a></li><li><a href=https://deploy-preview-296--mongodb-docs-csharp.netlify.app/fundamentals/crud/write-operations>fundamentals/crud/write-operations</a></li><li><a …
> DOCSP-44897 TOC relabel V3.0

- source/fundamentals/crud/read-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45443>
<li><a href=https://deploy-preview-298--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations>fundamentals/crud/read-operations</a></li>
> DOCSP-45443 Remaining TOC Changes

- source/fundamentals.txt
- source/fundamentals/connection/odata.txt
- source/fundamentals/odata.txt
- source/includes/code-examples/RestaurantOdata.cs
- source/includes/fundamentals/code-examples/connection/OData.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-32418
<li><a href=https://deploy-preview-286--mongodb-docs-csharp.netlify.app/fundamentals/odata>fundamentals/odata</a></li><li><a href=https://deploy-preview-286--mongodb-docs-csharp.netlify.app/fundamentals>fundamentals</a></li>
> DOCSP-32418 Add OData tutorial

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-45690
Output of `mut-redirects`:
`Redirect 301 /docs/drivers/csharp/v2.19/fundamentals/odata/ https://www.mongodb.com/docs/drivers/csharp/v2.19/
Redirect 301 /docs/drivers/csharp/v2.20/fundamentals/odata/ https://www.mongodb.com/docs/drivers/csharp/v2.20/
Redirect 301 /docs/drivers/csharp/v2.21/fundamentals/odata/ https://www.mongodb.com/docs/drivers/csharp/v2.21/
Redirect 301 /docs/drivers/csharp/v2.22/fundamentals/odata/ https://www.mongodb.com/docs/drivers/csharp/v2.22/
Redirect 301 /docs/drivers/csharp/v2.23/fundamentals/odata/ https://www.mongodb.com/docs/drivers/csharp/v2.23/
Redirect 301 /docs/drivers/csharp/v2.24/fundamentals/odata/ …
> DOCSP-45690 - Add oData redirect

- source/fundamentals.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45691
<li><a href=https://deploy-preview-331--mongodb-docs-csharp.netlify.app/fundamentals>fundamentals</a></li>
> DOCSP-45691 - Fix TOC

- source/fundamentals/transactions.txt
> Backports DOCSP-45749 to v3.0

- source/fundamentals/serialization/guid-serialization.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45824
<li><a href=https://deploy-preview-348--mongodb-docs-csharp.netlify.app/fundamentals/serialization/guid-serialization>fundamentals/serialization/guid-serialization</a></li>
> DOCSP-45824 Remove broken GUID link

- source/fundamentals/transactions.txt
> Backports DOCSP-45749 to v2.30

- source/fundamentals/transactions.txt
> Backports DOCSP-45749 to v2.29

- source/fundamentals/transactions.txt
> Backports DOCSP-45749 to v2.28

- source/fundamentals/transactions.txt
> Backports DOCSP-45749 to v2.25

- source/fundamentals/transactions.txt
> Backports DOCSP-45749 to v2.24

- source/fundamentals/transactions.txt
> Backports DOCSP-45749 to v2.23

- source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35829>
<li><a href=https://deploy-preview-367--mongodb-docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
> DOCSP-35829-new-distinctmany-method

- source/fundamentals/connection/connection-options.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37144
<li><a href=https://deploy-preview-362--mongodb-docs-csharp.netlify.app/fundamentals/connection/connection-options>fundamentals/connection/connection-options</a></li>
> DOCSP-37144: Server monitoring mode

- config/redirects
output of mut-redirects:
- Redirect 301 /docs/drivers/csharp/v2.22/fundamentals/authentication/oidc/ https://www.mongodb.com/docs/drivers/csharp/v2.22/fundamentals/authentication/
- Redirect 301 /docs/drivers/csharp/v2.23/fundamentals/authentication/oidc/ https://www.mongodb.com/docs/drivers/csharp/v2.23/fundamentals/authentication/
- Redirect 301 /docs/drivers/csharp/v2.24/fundamentals/authentication/oidc/ https://www.mongodb.com/docs/drivers/csharp/v2.24/fundamentals/authentication/
> OIDC redirect

- source/upgrade/v3.txt
JIRA - N/A
<li><a href=https://deploy-preview-412--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
> Fix typo in GUID to BSON mapping

- source/fundamentals/serialization/guid-serialization.txt
- source/upgrade/v3.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46397>
<li><a href=https://deploy-preview-409--mongodb-docs-csharp.netlify.app/fundamentals/serialization/guid-serialization>fundamentals/serialization/guid-serialization</a></li><li><a href=https://deploy-preview-409--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
> DOCSP-46397: Add CSUUID meta keyword

- source/fundamentals/crud/read-operations/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46469>
The $comment page no longer exists in the manual, so I've just clarified the description. The link below the table for FindOptions takes you to the general page so you can see the API docs, just like you can for the other options.
<li><a href=https://deploy-preview-415--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations/retrieve>fundamentals/crud/read-operations/retrieve</a></li>
> [C#] Internal 404 - $comment 404

- source/fundamentals/crud/write-operations/replace.txt
- source/includes/code-examples/replace-one/ReplaceOne.cs
- source/includes/code-examples/replace-one/ReplaceOneAsync.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-46303>
<li><a href=https://deploy-preview-406--mongodb-docs-csharp.netlify.app/fundamentals/crud/write-operations/replace>fundamentals/crud/write-operations/replace</a></li>
> DOCSP-46303 Update replace documents

- source/includes/code-examples/replace-one/ReplaceOne.cs
- source/includes/code-examples/replace-one/ReplaceOneAsync.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-46303>
No pages to preview
Staging - <https://deploy-preview-427--docs-csharp.netlify.app/fundamentals/crud/write-operations/replace/>
> [fix] Add comma to replace examples

- source/fundamentals/connection/connection-options.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46693>
[Connection Options](https://deploy-preview-444--docs-csharp.netlify.app/fundamentals/connection/connection-options/#connection-options-1)
> DOCSP-46693 AutoEncryptionOptions 404

- source/fundamentals/crud/read-operations/count.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46705>
<li><a href=https://deploy-preview-450--docs-csharp.netlify.app/fundamentals/crud/read-operations/count>fundamentals/crud/read-operations/count</a></li>
Specific spot: https://deploy-preview-450--docs-csharp.netlify.app/fundamentals/crud/read-operations/count/#api-documentation
> DOCSP-46705 404 EstimatedDocumentCount API link

- source/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46707>
<li><a href=https://deploy-preview-452--docs-csharp.netlify.app/quick-reference>quick-reference</a></li>
> DOCSP-46707 404 on Skip API link

- source/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46706>
<li><a href=https://deploy-preview-451--docs-csharp.netlify.app/quick-reference>quick-reference</a></li>
> DOCSP-46706 404 on Limit API link

- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-47153
<li><a href=https://deploy-preview-460--docs-csharp.netlify.app/whats-new>whats-new</a></li>
> DOCSP-47153 Projection optimization note

- source/faq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46728>
<li><a href=https://deploy-preview-459--docs-csharp.netlify.app/faq>faq</a></li>
Got inspoiration to add 'Technical' from this [AWS FAQ page](https://docs.aws.amazon.com/partner-central/latest/crm/technical-faq-fields.html). Don't think the title needs to be longer than this.
> DOCSP-46728 FAQ too short title

- source/fundamentals/crud/write-operations/update-many/arrays.txt
- source/fundamentals/crud/write-operations/update-many/fields.txt
- source/fundamentals/crud/write-operations/update-one/arrays.txt
- source/fundamentals/crud/write-operations/update-one/fields.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48222>
<li><a href=https://deploy-preview-502--docs-csharp.netlify.app/fundamentals/crud/write-operations/update-many/arrays>fundamentals/crud/write-operations/update-many/arrays</a></li><li><a href=https://deploy-preview-502--docs-csharp.netlify.app/fundamentals/crud/write-operations/update-many/fields>fundamentals/crud/write-operations/update-many/fields</a></li><li><a href=https://deploy-preview-502--docs-csharp.netlify.app/fundamentals/crud/write-operations/update-one/arrays>fundamentals/crud/write-operations/update-one/arrays</a></li><li><a href=https://deploy-preview-502--docs-csharp.netlify.app/fundamentals/crud/write-operations/update-one/fields>f …
> DOCSP-48222 - Duplicate page titles

- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-48297>
No pages to preview
> DOCSP-48297: Update snooty title

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48362>
<li><a href=https://deploy-preview-513--docs-csharp.netlify.app/whats-new>whats-new</a></li>
> DOCSP-48362 - Fix link

- source/fundamentals/atlas-search.txt
- source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-47263
https://deploy-preview-525--docs-csharp.netlify.app/fundamentals/atlas-search/#range
> DOCSP-47263 Atlas Search string range query

- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48488
https://deploy-preview-526--docs-csharp.netlify.app/whats-new/#what-s-new-in-3.3
> DOCSP-48488 NamespaceType

- source/fundamentals/connection/connect.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47829>
<li><a href=https://deploy-preview-523--docs-csharp.netlify.app/fundamentals/connection/connect>fundamentals/connection/connect</a></li>
> DOCSP-47829 - Note about Docker and replica sets

- source/fundamentals/atlas-search.txt
- source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-45702
<li><a href=https://deploy-preview-518--docs-csharp.netlify.app/fundamentals/atlas-search>fundamentals/atlas-search</a></li>
> DOCSP-45702: Atlas search pagination

- source/usage-examples/insertMany.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48977>
> DOCSP-48977: fix dead link

- source/fundamentals/authentication/x509.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49301>
<li><a href=https://deploy-preview-590--docs-csharp.netlify.app/fundamentals/authentication/x509>fundamentals/authentication/x509</a></li>
> DOCSP-49301 Fix X.509 MongoCredential code example

- source/fundamentals/authentication/x509.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49360>
<li><a href=https://deploy-preview-605--docs-csharp.netlify.app/fundamentals/authentication/x509>fundamentals/authentication/x509</a></li>
> DOCSP-49360 Update punctuation in code snippet

- source/includes/mongodb-compatibility-table-csharp.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-50276>
No pages to preview
> DOCSP-50276 - Fix footnote name

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49745>
https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/#examples
- [] Are the page titles greater than 20 characters long and [SEO relevant](https://docs.google.com/spreadsheets/d/1Wkt0-5z04KmcMNscN5bjUKnzwWAtMq9VESp-Lz6r2o8/edit?usp=sharing)?
> DOCSP-49745: geoNear manual link

- source/fundamentals/authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50729>
<li><a href=https://deploy-preview-652--docs-csharp.netlify.app/fundamentals/authentication>fundamentals/authentication</a></li>
> DOCSP-50729-remove-duplicate-metadata

- source/crud/restful-api-tutorial.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-52059>
<li><a href=https://deploy-preview-661--docs-csharp.netlify.app/crud/restful-api-tutorial>crud/restful-api-tutorial</a></li>
> DOCSP-52059 RESTful API Title

- source/fundamentals/crud/write-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-51304>
<li><a href=https://deploy-preview-662--mongodb-docs-csharp.netlify.app/fundamentals/crud/write-operations>fundamentals/crud/write-operations</a></li>
> DOCSP-51304 - Add noindex to write-operations

- snooty.toml
- source/fundamentals/connection.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-51241, https://jira.mongodb.org/browse/DOCSP-51243
<li><a href=https://deploy-preview-668--docs-csharp.netlify.app/fundamentals/connection>fundamentals/connection</a></li><li><a href=https://deploy-preview-668--docs-csharp.netlify.app/fundamentals/crud/read-operations>fundamentals/crud/read-operations</a></li>
> DOCSP-51241: Short pages fixes

- .github/pull_request_template.md
- README.rst
Redirect users to the monorepo.
> [C#] Add monorepo notification
