source/fundamentals/connection/connection-options.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/connection-options-indentation-fixes/
=> fix indentatation in connection options page

config/redirects, source/fundamentals/connection/network-compression.txt
Removes orphan page (network-compression.txt) that is not referenced anywhere, but is blank. This page is receiving page views and is indexed on Google. It should be removed until content can be created.
JIRA - None
Staging - (nothing to be shown)
https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-29771-meta/
mut-redirects output
```
Redirect 301 /docs/drivers/csharp/2.19/fundamentals/connection/network-compression/ https://www.mongodb.com/docs/drivers/csharp/2.19/
Redirect 301 /docs/drivers/csharp/master/fundamentals/connection/network-compression/ https://www.mongodb.com/docs/drivers/csharp/master/
```
=> Remove orphan page with no content

source/compatibility.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/v2.20/compatibility/)
=> replace v2.20 compat tables with sharedincludes

source/usage-examples.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/findMany.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27681
Staging - https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-27681-move-sample-classes/usage-examples/
- [] Did you run a grammar-check?
=> docsp-27681 - move example classes

source/quick-start.txt
The difference between single and double quotes is more significant in bash, which would account for the difference in processing the statements listed in the ticket:
```bash
export MONGODB_URI='<your MongoDB URI>'
```
and
```bash
set MONGODB_URI="<your MongoDB URI>"
```
Since `export` sets a global variable, and no `set` options are being used, I think `export` is more universally useful in this situation.
JIRA - <https://jira.mongodb.org/browse/DOCSP-37263>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-37263/quick-start/>
=> Add Option for 'set' command for Environment Variables along with Export

source/fundamentals/atlas-search.txt, source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-37267>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-37267/fundamentals/atlas-search/#std-label-csharp-atlas-search>
=> [C#] Code Snippet for Atlas Search Autocomplete doesn't work

source/previous-versions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38781>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/csharp/DOCSP-38781-remove-1.11-link/previous-versions/
=> DOCSP-38781: remove v1.11 link

source/fundamentals/connection/tls.txt
Added note to C# driver guide on configuring TLS/SSL connections. Modeled after a [similar note in the Java driver guide for the same configurations](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/tls/).
JIRA - <https://jira.mongodb.org/browse/DOCSP-34013>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-34013-csharp-TLS-default/fundamentals/connection/tls/>
=> DOCSP-34013: Add DNS seedlist default behavior to C# TLS/SSL guide

source/fundamentals/serialization.txt, source/fundamentals/serialization/poco.txt, source/includes/fundamentals/code-examples/Clothing.cs
Addressing two code-sample related subtasks from DOCSP-37272. Confirmed that code samples work correctly by testing using my local setup.
JIRA
* [DOCSP-39026](https://jira.mongodb.org/browse/DOCSP-39026): Include DateTime and Dictionary-type attributes to POCO example
* [DOCSP-39023](https://jira.mongodb.org/browse/DOCSP-39023): Fix code snippet incorrectly referencing "RegularExpression" instead of "Regex"
Staging
* [DOCSP-39026](https://jira.mongodb.org/browse/DOCSP-39026): <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-37272-code-examples/fundamentals/serialization/poco/>
* [DOCSP-39023](https://jira.mongodb.org/browse/DOCSP-39023): …
=> DOCSP-37272: Update and correct serialization-related code examples

source/includes/code-examples/delete-many/DeleteMany.cs, source/includes/code-examples/delete-many/DeleteManyAsync.cs, source/includes/code-examples/delete-one/DeleteOne.cs, source/includes/code-examples/delete-one/DeleteOneAsync.cs, source/includes/code-examples/find-many/FindMany.cs, source/includes/code-examples/find-many/FindManyAsync.cs, source/includes/code-examples/find-one/FindOne.cs, source/includes/code-examples/find-one/FindOneAsync.cs, source/includes/code-examples/insert-many/InsertMany.cs, source/includes/code-examples/insert-many/InsertManyAsync.cs, source/includes/code-examples/insert-one/InsertOne.cs, source/includes/code-examples/insert-one/InsertOneAsync.cs, source/includes/code-examples/replace-one/ReplaceOne.cs, source/includes/code-examples/replace-one/ReplaceOneAsync.cs, source/includes/code-examples/update-many/UpdateMany.cs, source/includes/code-examples/update-many/UpdateManyAsync.cs, source/includes/code-examples/update-one/UpdateOne.cs, source/includes/code-examples/update-one/UpdateOneAsync.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-37266>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-37266-error-handling-examples/usage-examples/>
=> DOCSP-37266: Add try-catch logic to code samples

source/fundamentals.txt, source/fundamentals/transactions.txt, source/includes/fundamentals/code-examples/Transaction.cs
JIRA - <[DOCSP-37469](https://jira.mongodb.org/browse/DOCSP-37469)>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-37469-transactions-v2/fundamentals/transactions/>
=> DOCSP-37469: Add transactions page

source/fundamentals.txt, source/fundamentals/database-collection.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-27283>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCSP-27283-class-overview/fundamentals/database-collection/
=> DOCSP-27283: db coll page

snooty.toml, source/fundamentals/enterprise-authentication.txt, source/fundamentals/stable-api.txt, source/index.txt, source/upgrade.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39194
Staging - https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-39194-mdb-server/fundamentals/enterprise-authentication/#mongodb-oidc
=> DOCSP-39194 - Add MDB Server constant

source/fundamentals/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39359
Staging - https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-39359-oidc-gcp/fundamentals/enterprise-authentication/#gcp-imds
=> DOCSP-39359 - GCP OIDC

source/fundamentals.txt, source/fundamentals/indexes.txt, source/includes/fundamentals/code-examples/Indexes.cs
JIRA - [DOCSP-32634](https://jira.mongodb.org/browse/DOCSP-32634)
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-32634-indexes/fundamentals/indexes/>
=> DOCSP-32634: Add Indexes page

source/fundamentals.txt, source/fundamentals/builders.txt, source/fundamentals/geo.txt, source/fundamentals/indexes.txt, source/fundamentals/linq.txt
Largely based off the [Go version](https://www.mongodb.com/docs/drivers/go/upcoming/fundamentals/geo/) of the page, with a little [Java version](https://www.mongodb.com/docs/drivers/java/sync/upcoming/fundamentals/crud/read-operations/geo/) sprinkled in.
JIRA - <https://jira.mongodb.org/browse/DOCSP-40574>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/csharp/docsworker-xlarge/DOCSP-40574-geo/fundamentals/geo>
=> DOCSP-40574: Add Geospatial page

source/upgrade.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41883
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/csharp/DOCSP-41883-binding-redirects/upgrade/#version-2.28.0-potential-breaking-change
https://preview-mongodbjordansmith721.gatsbyjs.io/csharp/DOCSP-41883-binding-redirects/whats-new/#what-s-new-in-2.28
=> DOCSP-41883 Show binding redirects on upgrade page

source/connection-troubleshooting.txt, source/fundamentals/authentication.txt, source/fundamentals/connection/network-compression.txt, source/fundamentals/connection/tls.txt, source/fundamentals/enterprise-authentication.txt, source/quick-start.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42375>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/csharp/DOCSP-42303-username-password/>
=> DOCSP-42303: Change username and password copy

source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCS-16824>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/csharp/DOCS-16824-lookup-result-reformat/fundamentals/linq/#-lookup
=> DOCS-16824: fix lookup output

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/change-streams.txt, source/includes/code-examples/change-streams/change-streams.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-34027
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/csharp/DOCSP-34027-change-streams/fundamentals/crud/read-operations/change-streams/
=> DOCSP-34027 Change Streams

source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43103
Staging - https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-43103-version-note/upgrade/#version-2.28.0-potential-breaking-change
=> DOCSP-43103 - v2.28 breaking change note

source/fundamentals/connection/connection-options.txt, source/fundamentals/transactions.txt
[Nested Component Fixes](https://docs.google.com/document/d/1yMbng-EPOQ82bAzBTC2VJwIvsUBOSCJh21cGbDoe1a8/edit)
JIRA - https://jira.mongodb.org/browse/DOCSP-42959
Staging:
- https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-42959-nested-components/fundamentals/connection/connection-options/
- https://preview-mongodbmongokart.gatsbyjs.io/csharp/docsp-42959-nested-components/fundamentals/transactions/#methods
=> DOCSP-42959 - Nested Components

.github/workflows/copy-compat-to-docs-shared.yml, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41828
<li><a href=https://deploy-preview-230--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-41828 - Remove legacy package

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43582
<li><a href=https://deploy-preview-238--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-43582 - Half type

source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43525
<li><a href=https://deploy-preview-240--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
=> DOCSP-43525 - Decimal128

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43047
<li><a href=https://deploy-preview-244--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-43047 - DateOnly/TimeOnly

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43829
<li><a href=https://deploy-preview-241--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-43829 - Disposable IMongoClient

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43911
<li><a href=https://deploy-preview-242--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-43911 - Implicit Client-Side Projection

source/fundamentals/serialization/poco.txt, source/upgrade/v3.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44196
<li><a href=https://deploy-preview-251--mongodb-docs-csharp.netlify.app/fundamentals/serialization/poco>fundamentals/serialization/poco</a></li><li><a href=https://deploy-preview-251--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
=> DOCSP-44196 - NaN/Infinity serialization exception

config/redirects
The upgrade v2/v3 pages were added in the v3.0 docs. Redirects needed to prevent navigation to those pages in versions before v3.0.
Output of `mut redirects`:
`Redirect 301 /docs/drivers/csharp/v2.19/upgrade/v2/ https://www.mongodb.com/docs/drivers/csharp/v2.19/upgrade/
Redirect 301 /docs/drivers/csharp/v2.20/upgrade/v2/ https://www.mongodb.com/docs/drivers/csharp/v2.20/upgrade/
Redirect 301 /docs/drivers/csharp/v2.21/upgrade/v2/ https://www.mongodb.com/docs/drivers/csharp/v2.21/upgrade/
Redirect 301 /docs/drivers/csharp/v2.22/upgrade/v2/ https://www.mongodb.com/docs/drivers/csharp/v2.22/upgrade/
Redirect 301 /docs/drivers/csharp/v2.23/upgrade/v2/ https://www.mongodb.com/docs/drivers/csharp/v2.23/upgrade/
Redirect 301 /docs/drivers/csharp/v2.24/upgrade/v2/ …
=> DOCSP-44527 - v3 Upgrade redirects

source/whats-new.txt
These versions have reached their end-of-life per the archival policy (linked in Epic). Release notes for these versions and all earlier versions should also be removed from current versions (v2.21 and later). This preserves the changelog information in the original versions (e.g. v2.19 notes are in the v2.19 "What's New", but not later versions).
JIRA - <https://jira.mongodb.org/browse/DOCSP-44251>
STAGING - <https://deploy-preview-262--mongodb-docs-csharp.netlify.app/whats-new/>
=> (DOCSP-44251) [C#] Remove EOL v2.19 & v2.20 from "What's New" for v2.21+

.github/workflows/vale-tdbx.yml, source/fundamentals/linq.txt, source/includes/convention-pack-note.rst, source/includes/fundamentals/code-examples/linq.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-34044>
<li><a href=https://deploy-preview-253--mongodb-docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-34044: Add bitwise operators to aggregation pipeline

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44661
<li><a href=https://deploy-preview-281--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-44661 Update incorrect whats new bullet

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44845
<li><a href=https://deploy-preview-283--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-44845 - Fix tip box

source/fundamentals/builders.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39979
<li><a href=https://deploy-preview-288--mongodb-docs-csharp.netlify.app/fundamentals/builders/#array-operators>fundamentals/builders</a></li>
=> DOCSP-39979 Add example for ElemMatch builder

snooty.toml, source/fundamentals/aggregation.txt, source/fundamentals/crud/read-operations/change-streams.txt, source/fundamentals/database-collection.txt, source/fundamentals/indexes.txt, source/fundamentals/time-series.txt, source/fundamentals/transactions.txt, source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45274
=> DOCSP-45274 - v2.21 EOL

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/distinct.txt, source/includes/fundamentals/code-examples/Distinct.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-45007>
<li><a href=https://deploy-preview-292--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations/distinct>fundamentals/crud/read-operations/distinct</a></li><li><a href=https://deploy-preview-292--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations>fundamentals/crud/read-operations</a></li>
=> DOCSP-45007: Distinct

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/specify-documents-to-return.txt, source/includes/fundamentals/code-examples/LimitSortSkip.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-45005>
<li><a href=https://deploy-preview-290--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations/specify-documents-to-return>fundamentals/crud/read-operations/specify-documents-to-return</a></li><li><a href=https://deploy-preview-290--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations>fundamentals/crud/read-operations</a></li>
=> DOCSP-45005: Specify Docs to Return

source/compatibility.txt, source/fundamentals/encrypt-fields.txt, source/includes/include-fixes/compatibility-table-legend.rst, source/includes/include-fixes/encrypt-fields.rst, source/includes/include-fixes/lifecycle-schedule-callout.rst
(cherry picked from commit 3e27bfc76438796f9852e38dd5a81272e15a77ae)
=> Temporary includes fix (#299)

source/fundamentals.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/serialization.txt, source/index.txt, source/upgrade.txt, source/usage-examples.txt
* DOCSP-44897 TOC Relabel
* encryption rendering issue
* encryption still not rendering
(cherry picked from commit c48dd6efc513091ed27c9a8855dca8aa6d16d88d)
<li><a href=https://deploy-preview-311--mongodb-docs-csharp.netlify.app/fundamentals>fundamentals</a></li><li><a href=https://deploy-preview-311--mongodb-docs-csharp.netlify.app/fundamentals/connection>fundamentals/connection</a></li><li><a href=https://deploy-preview-311--mongodb-docs-csharp.netlify.app/fundamentals/crud>fundamentals/crud</a></li><li><a href=https://deploy-preview-311--mongodb-docs-csharp.netlify.app/fundamentals/crud/write-operations>fundamentals/crud/write-operations</a></li …
=> [Backport v2.29] DOCSP-44897 TOC Relabel (#287)

snooty.toml, source/fundamentals/database-collection.txt, source/fundamentals/databases-collections/run-command.txt, source/includes/fundamentals/code-examples/databases-collections/RunCommand.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-45004>
<li><a href=https://deploy-preview-320--mongodb-docs-csharp.netlify.app/fundamentals/databases-collections/run-command>fundamentals/databases-collections/run-command</a></li><li><a href=https://deploy-preview-320--mongodb-docs-csharp.netlify.app/fundamentals/database-collection>fundamentals/database-collection</a></li>
=> DOCSP-45004: Run Command

source/fundamentals.txt, source/fundamentals/read-write-configuration.txt, source/includes/fundamentals/code-examples/ReplicaSetConfigs.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-45010>
<li><a href=https://deploy-preview-322--mongodb-docs-csharp.netlify.app/fundamentals/read-write-configuration>fundamentals/read-write-configuration</a></li><li><a href=https://deploy-preview-322--mongodb-docs-csharp.netlify.app/fundamentals>fundamentals</a></li>
=> DOCSP-45010: Replica Set Operations

source/fundamentals/serialization/poco.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44180>
<li><a href=https://deploy-preview-323--mongodb-docs-csharp.netlify.app/fundamentals/serialization/poco>fundamentals/serialization/poco</a></li>
=> DOCSP-44180: Clarify _id field behavior for nested documents

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45693
<li><a href=https://deploy-preview-332--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-45693 - Remove EOL docs from What's New

source/fundamentals/transactions.txt
No changes to existing content except denesting from within admonitions.
JIRA - https://jira.mongodb.org/browse/DOCSP-45749
https://deploy-preview-343--mongodb-docs-csharp.netlify.app/fundamentals/transactions/#methods
=> (DOCSP-45749) Updates nested important admonitions to denest

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44733
<li><a href=https://deploy-preview-341--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-44733 - Immutable-collection serializers

source/fundamentals/serialization/polymorphic-objects.txt, source/upgrade/v3.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44706
<li><a href=https://deploy-preview-342--mongodb-docs-csharp.netlify.app/fundamentals/serialization/polymorphic-objects>fundamentals/serialization/polymorphic-objects</a></li><li><a href=https://deploy-preview-342--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li><li><a href=https://deploy-preview-342--mongodb-docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-44706 - Type discriminator note

source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36080>
<li><a href=https://deploy-preview-363--mongodb-docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-36080: Add DateFromString to list of supported LINQ methods

source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35833>
<li><a href=https://deploy-preview-364--mongodb-docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-35833: New LINQ methods

source/fundamentals/atlas-search.txt, source/includes/fundamentals/code-examples/atlas-search/AtlasSearchExamples.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-35724>
<li><a href=https://deploy-preview-372--mongodb-docs-csharp.netlify.app/fundamentals/atlas-search>fundamentals/atlas-search</a></li>
=> DOCSP-35724: $in operator documentation

source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40654>
<li><a href=https://deploy-preview-360--mongodb-docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-40654-sample-aggregation-operator

source/fundamentals/linq.txt
<li><a href=https://deploy-preview-378--mongodb-docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> V3.0-backports

source/fundamentals/transactions.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45870
<li><a href=https://deploy-preview-379--mongodb-docs-csharp.netlify.app/fundamentals/transactions>fundamentals/transactions</a></li>
=> DOCSP-45870 - Parallelism note

source/fundamentals/linq.txt, source/includes/fundamentals/code-examples/linq.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-40066>
- https://deploy-preview-373--mongodb-docs-csharp.netlify.app/fundamentals/linq/#nested-statements
=> DOCSP-40066: Support SelectMany inside Project/Select

source/fundamentals/builders.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42611>
<li><a href=https://deploy-preview-375--mongodb-docs-csharp.netlify.app/fundamentals/builders>fundamentals/builders</a></li>
=> DOCSP-42611: Filter Inject() example

source/fundamentals/crud/read-operations/change-streams.txt, source/includes/code-examples/change-streams/change-streams.cs
JIRA - https://jira.mongodb.org/browse/DOCSP-34008
<li><a href=https://deploy-preview-374--mongodb-docs-csharp.netlify.app/fundamentals/crud/read-operations/change-streams>fundamentals/crud/read-operations/change-streams</a></li>
=> DOCSP-34008: Split large change events

source/upgrade/v3.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46293
<li><a href=https://deploy-preview-408--mongodb-docs-csharp.netlify.app/upgrade/v3>upgrade/v3</a></li>
=> DOCSP-46293 Add GUID to BSON mapping bullet

source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46235>
<li><a href=https://deploy-preview-441--docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-46235: Add links to LINQ in API docs

source/faq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46684>
Seems like there is no more ``MongoServerSettings`` for newer versions and got rid of "legacy" in url.
<li><a href=https://deploy-preview-440--mongodb-docs-csharp.netlify.app/faq>faq</a></li>
=> DOCSP-46684 404 server selection timeout API

source/upgrade/v3.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46065>
https://deploy-preview-439--docs-csharp.netlify.app/upgrade/v3/
=> DOCSP-46065: GUID serialization breaking change note

source/faq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46795>
<li><a href=https://deploy-preview-449--docs-csharp.netlify.app/faq>faq</a></li>
=> DOCSP-46795: Update LINQ/builder FAQ

source/fundamentals/serialization.txt, source/fundamentals/serialization/poco.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45822
<li><a href=https://deploy-preview-447--docs-csharp.netlify.app/fundamentals/serialization>fundamentals/serialization</a></li><li><a href=https://deploy-preview-447--docs-csharp.netlify.app/fundamentals/serialization/poco>fundamentals/serialization/poco</a></li><li><a href=https://deploy-preview-447--docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-45822 Add convention packs section

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46310
<li><a href=https://deploy-preview-448--docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-46310 EnumRepresentationConvention constructor update

source/fundamentals/authentication/ldap.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46729>
Title as used on Server docs: https://www.mongodb.com/docs/manual/core/security-ldap/
[LDAP](https://deploy-preview-472--docs-csharp.netlify.app/fundamentals/authentication/ldap/)
=> DOCSP-46729 Too Short Title: LDAP

source/fundamentals/linq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46455>
<li><a href=https://deploy-preview-473--docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-46455 Too Short Title: LINQ

source/fundamentals/serialization/polymorphic-objects.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47960>
https://deploy-preview-497--docs-csharp.netlify.app/fundamentals/serialization/polymorphic-objects/
=> DOCSP-47960: Remove ScalarDiscriminator limitation admonition

source/fundamentals/builders.txt, source/fundamentals/linq.txt, source/includes/vector-search-intro.rst, source/includes/vector-search-parameters.rst
`Exact` property will be backported only back to v3.1.
JIRA - <https://jira.mongodb.org/browse/DOCSP-45048>
<li><a href=https://deploy-preview-517--docs-csharp.netlify.app/fundamentals/builders>fundamentals/builders</a></li><li><a href=https://deploy-preview-517--docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-45048 - Vector search params

source/fundamentals/linq.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46188
<li><a href=https://deploy-preview-522--docs-csharp.netlify.app/fundamentals/linq>fundamentals/linq</a></li>
=> DOCSP-46188 Add Lookup() method to LINQ docs

source/fundamentals/crud/read-operations/change-streams.txt, source/fundamentals/crud/read-operations/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47834>
<li><a href=https://deploy-preview-524--docs-csharp.netlify.app/fundamentals/crud/read-operations/change-streams>fundamentals/crud/read-operations/change-streams</a></li><li><a href=https://deploy-preview-524--docs-csharp.netlify.app/fundamentals/crud/read-operations/retrieve>fundamentals/crud/read-operations/retrieve</a></li>
=> DOCSP-47834 clarify batch size

source/fundamentals/crud/read-operations/change-streams.txt, source/fundamentals/crud/read-operations/distinct.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/write-operations/bulk-write.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/database-collection.txt, source/fundamentals/databases-collections/run-command.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/findMany.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45384>
<li><a href=https://deploy-preview-538--docs-csharp.netlify.app/fundamentals/crud/read-operations/change-streams>fundamentals/crud/read-operations/change-streams</a></li><li><a href=https://deploy-preview-538--docs-csharp.netlify.app/fundamentals/crud/read-operations/distinct>fundamentals/crud/read-operations/distinct</a></li><li><a href=https://deploy-preview-538--docs-csharp.netlify.app/fundamentals/crud/read-operations/retrieve>fundamentals/crud/read-operations/retrieve</a></li><li><a href=https://deploy-preview-538--docs-csharp.netlify.app/fundamentals/crud/write-operations/bulk-write>fundamentals/crud/write-operations/bulk-write</a></li><li><a …
=> move sync above async

source/fundamentals/builders.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48120>
- [builders page](https://deploy-preview-537--docs-csharp.netlify.app/fundamentals/builders/#array-operators)
- [whats new](https://deploy-preview-537--docs-csharp.netlify.app/whats-new/#what-s-new-in-3.3)
=> DOCSP-48120: elemmatch method overload

source/fundamentals/linq.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48356>
linq guide [takewhile](https://deploy-preview-536--docs-csharp.netlify.app/fundamentals/linq/#limit-on-a-condition) | [skipwhile](https://deploy-preview-536--docs-csharp.netlify.app/fundamentals/linq/#skip-on-a-condition) | [table](https://deploy-preview-536--docs-csharp.netlify.app/fundamentals/linq/#supported-methods)
[whats new](https://deploy-preview-536--docs-csharp.netlify.app/whats-new/#what-s-new-in-3.3)
=> DOCSP-48356: skipwhile & takewhile

source/fundamentals/crud/write-operations/update-many.txt, source/fundamentals/crud/write-operations/update-many/fields.txt, source/fundamentals/crud/write-operations/update-one.txt, source/fundamentals/crud/write-operations/update-one/fields.txt, source/includes/code-examples/update-many/UpdateManyFields.cs, source/includes/code-examples/update-one/UpdateOneFields.cs, source/includes/page-templates/update/fields.rst, source/includes/page-templates/update/update.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-45799>
- [update one](https://deploy-preview-583--docs-csharp.netlify.app/fundamentals/crud/write-operations/update-one/fields/)
- [update many](https://deploy-preview-583--docs-csharp.netlify.app/fundamentals/crud/write-operations/update-many/fields/)
=> DOCSP-45799: code examples for fields update pages

source/fundamentals/atlas-search.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48252>
[Autocomplete section](https://deploy-preview-586--docs-csharp.netlify.app/fundamentals/atlas-search/#autocomplete) in AS guide
=> DOCSP-48252: autocomplete index link/note

source/crud/query/cursors.txt, source/includes/fundamentals/code-examples/Cursor.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-49067>
<li><a href=https://deploy-preview-584--docs-csharp.netlify.app/crud/query/cursors>crud/query/cursors</a></li>
=> DOCSP-49067: Cursors

source/crud/configure.txt, source/includes/fundamentals/code-examples/ReplicaSetConfigs.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-49095>
<li><a href=https://deploy-preview-585--docs-csharp.netlify.app/crud/configure>crud/configure</a></li>
=> DOCSP-49095: Retryable Reads and Writes

source/fundamentals/crud/write-operations/replace.txt, source/includes/page-templates/update/update.rst, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45429>
1. [update](https://deploy-preview-581--docs-csharp.netlify.app/fundamentals/crud/write-operations/update-one/#configuration-options)
2. [replace](https://deploy-preview-581--docs-csharp.netlify.app/fundamentals/crud/write-operations/replace/#customize-the-replace-operation)
3. [whats new](https://deploy-preview-581--docs-csharp.netlify.app/whats-new/#what-s-new-in-3.1)
=> DOCSP-45429: sort for update and replace one

source/fundamentals/linq.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49279>
1. [linq section](https://deploy-preview-604--docs-csharp.netlify.app/fundamentals/linq/#-convert)
2. [whats new](https://deploy-preview-604--docs-csharp.netlify.app/whats-new/#std-label-csharp-version-3.4)
=> DOCSP-49279: $convert stage LINQ method

snooty.toml, source/fundamentals/indexes.txt, source/fundamentals/indexes/search-indexes.txt, source/includes/fundamentals/code-examples/SearchIndexes.cs, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45054>
- [new page](https://deploy-preview-580--docs-csharp.netlify.app/fundamentals/indexes/search-indexes/)
- [whats new](https://deploy-preview-580--docs-csharp.netlify.app/whats-new/#what-s-new-in-3.1)
=> DOCSP-45054: search index type

source/fundamentals/connection/connection-options.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37452>
<li><a href=https://deploy-preview-593--docs-csharp.netlify.app/fundamentals/connection/connection-options>fundamentals/connection/connection-options</a></li><li><a href=https://deploy-preview-593--docs-csharp.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-37452: srvServiceName cxn opt

source/connect/connection-options/connection-pools.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49058>
<li><a href=https://deploy-preview-616--docs-csharp.netlify.app/connect/connection-options/connection-pools>connect/connection-options/connection-pools</a></li>
=> DOCSP-49058: Connection Pools

source/aggregation/stages.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49635>
<li><a href=https://deploy-preview-624--docs-csharp.netlify.app/aggregation/stages>aggregation/stages</a></li>
=> DOCSP-49635 - Aggregation stages fix

source/data-formats/extended-json.txt, source/includes/fundamentals/code-examples/ExtendedJson.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-49078>
<li><a href=https://deploy-preview-619--docs-csharp.netlify.app/data-formats/extended-json>data-formats/extended-json</a></li>
=> DOCSP-49078: Extended JSON

source/security/authentication/aws-iam.txt, source/security/authentication/kerberos.txt, source/security/authentication/ldap.txt, source/security/authentication/oidc.txt, source/security/authentication/scram.txt, source/security/authentication/x509.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49089>
<li><a href=https://deploy-preview-625--docs-csharp.netlify.app/security/authentication/aws-iam>security/authentication/aws-iam</a></li><li><a href=https://deploy-preview-625--docs-csharp.netlify.app/security/authentication/kerberos>security/authentication/kerberos</a></li><li><a href=https://deploy-preview-625--docs-csharp.netlify.app/security/authentication/ldap>security/authentication/ldap</a></li><li><a href=https://deploy-preview-625--docs-csharp.netlify.app/security/authentication/oidc>security/authentication/oidc</a></li><li><a href=https://deploy-preview-625--docs-csharp.netlify.app/security/authentication/scram>security/authentication/scra …
=> DOCSP-49089 - Authentication (Comprehensive Coverage)

source/crud/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49096>
<li><a href=https://deploy-preview-579--docs-csharp.netlify.app/crud/transactions>crud/transactions</a></li>
=> DOCSP-49096: Causal Consistency note

source/indexes.txt, source/reference/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49082>
<li><a href=https://deploy-preview-623--docs-csharp.netlify.app/indexes>indexes</a></li><li><a href=https://deploy-preview-623--docs-csharp.netlify.app/reference/quick-reference>reference/quick-reference</a></li>
=> DOCSP-49082 - Indexes (Comprehensive Coverage)

config/redirects, source/crud/query.txt, source/crud/query/query-filter.txt, source/crud/query/specify-query.txt, source/includes/fundamentals/code-examples/specify-query/FindAndBuilder.cs, source/includes/fundamentals/code-examples/specify-query/FindAndPOCO.cs, source/includes/fundamentals/code-examples/specify-query/FindEqBuilder.cs, source/includes/fundamentals/code-examples/specify-query/FindEqPOCO.cs, source/includes/fundamentals/code-examples/specify-query/FindExistsBuilder.cs, source/includes/fundamentals/code-examples/specify-query/FindGtBuilder.cs, source/includes/fundamentals/code-examples/specify-query/FindGtPOCO.cs, source/includes/fundamentals/code-examples/specify-query/FindRegexBuilder.cs, source/includes/fundamentals/code-examples/specify-query/FindSizeBuilder.cs, source/reference/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49061>
<li><a href=https://deploy-preview-620--docs-csharp.netlify.app/crud/query/query-filter>crud/query/query-filter</a></li><li><a href=https://deploy-preview-620--docs-csharp.netlify.app/crud/query>crud/query</a></li><li><a href=https://deploy-preview-620--docs-csharp.netlify.app/reference/compatibility>reference/compatibility</a></li>
=> DOCSP-49061 - Query filters (Comprehensive Coverage)

source/crud/bulk-write.txt, source/crud/delete.txt, source/crud/query/count.txt, source/crud/query/distinct.txt, source/crud/query/find.txt, source/crud/replace.txt, source/includes/collation.rst, source/includes/page-templates/update/update.rst, source/logging-and-monitoring/change-streams.txt
I wanted to incorporate this into the Server docs but it didn't fit there neatly.
JIRA - <https://jira.mongodb.org/browse/DOCSP-49849>
<li><a href=https://deploy-preview-628--docs-csharp.netlify.app/crud/bulk-write>crud/bulk-write</a></li><li><a href=https://deploy-preview-628--docs-csharp.netlify.app/crud/delete>crud/delete</a></li><li><a href=https://deploy-preview-628--docs-csharp.netlify.app/crud/query/count>crud/query/count</a></li><li><a href=https://deploy-preview-628--docs-csharp.netlify.app/crud/query/distinct>crud/query/distinct</a></li><li><a href=https://deploy-preview-628--docs-csharp.netlify.app/crud/query/find>crud/query/find</a></li><li><a …
=> DOCSP-49849 - Collation

source/data-formats/extended-json.txt, source/includes/fundamentals/code-examples/ExtendedJson.cs
JIRA - <https://jira.mongodb.org/browse/DOCSP-49867>
<li><a href=https://deploy-preview-636--docs-csharp.netlify.app/data-formats/extended-json>data-formats/extended-json</a></li>
=> DOCSP-49867: Add JsonReader example

source/fundamentals/authentication/oidc.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50554>
<li><a href=https://deploy-preview-648--docs-csharp.netlify.app/fundamentals/authentication/oidc>fundamentals/authentication/oidc</a></li>
=> DOCSP-50554: Add extra AWS info to OIDC page
